<a href="https://colab.research.google.com/github/Sarkis55/UHC-and-Population-Health-Outcomes-Analysis-SDG-3-/blob/main/UHC_and_Population_Health_Outcomes_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Does Universal Health Care Coverage Improve Population Health Outcome?

To what extent does the UHC Service Coverage Index (SDG 3.8.1) predict differences in key population health outcomes across countries? This analysis will test whether higher UHC coverage levels are associated with lower maternal mortality (3.1.1), reduced under-5 mortality (3.2.1), and decreased premature mortality from noncommunicable diseases (3.4.1). The study will compare countries across regions and income groups to assess the strength, direction, and consistency of these relationships. Findings will clarify whether improvements in health coverage systematically align with better national health outcomes.

In [1]:
import pandas as pd
import requests

In [2]:
#Loading entire SDG Data via the UNSD SDG API
series_url = "https://unstats.un.org/SDGAPI/v1/sdg/Series/List"
series = requests.get(series_url).json()
series_df = pd.DataFrame(series)
series_df.head()

,goal,target,indicator,release,code,description,uri
0,"[15, 15]","[15.a, 15.b]","[15.a.1, 15.b.1]",2025.Q4.G.02,DC_ODA_BDVDL,Total official development assistance for biod...,/v1/sdg/Series/DC_ODA_BDVDL
1,[3],[3.b],[3.b.2],2025.Q4.G.02,DC_TOF_HLTHNT,Total official development assistance to medic...,/v1/sdg/Series/DC_TOF_HLTHNT
2,[9],[9.a],[9.a.1],2025.Q4.G.02,DC_TOF_INFRAL,"Total official flows for infrastructure, by re...",/v1/sdg/Series/DC_TOF_INFRAL
3,[4],[4.b],[4.b.1],2025.Q4.G.02,DC_TOF_SCHIPSL,"Total official flows for scholarships, by reci...",/v1/sdg/Series/DC_TOF_SCHIPSL
4,[8],[8.a],[8.a.1],2025.Q4.G.02,DC_TOF_TRDCMDL,Total official flows (commitments) for Aid for...,/v1/sdg/Series/DC_TOF_TRDCMDL

In [3]:
#Since we are only concerned with Goal #3, Good Health and Well-Being,
#we filter down to the series relating to health.

health_series = series_df[series_df['code'].str.startswith("SH_", na = False)].copy()
health_series[['code', 'description']].head(100)

                     code                                        description
34            SH_DTH_NCOM  Mortality rate attributed to cardiovascular di...
35           SH_DYN_IMRTN                             Infant deaths (number)
36            SH_DYN_MORT  Under-five mortality rate, by sex (deaths per ...
37           SH_DYN_NMRTN                           Neonatal deaths (number)
38            SH_H2O_SAFE  Proportion of population using safely managed ...
..                    ...                                                ...
592        SH_STA_WASHARI  Mortality rate attributed to unsafe water, uns...
682       SH_MDD_WMN_NPRG  Prevalence of minimum dietary diversity among ...
695           SH_MDD_CHLD  Prevalence of minimum dietary diversity among ...
696  SH_OOP_XPD_EARNNET40  Proportion of the population with positive out...
697        SH_ACS_UNHC_25  Universal health coverage (UHC) service covera...

[75 rows x 2 columns]

In [4]:
#Function that takes the SDG API and returns back the contents of the desired series

def get_content(url, data_dict):
  r = requests.post(
      url,
      headers = {
          "Accept": "application-octet-stream",
          "Content-Type": "application/x-www-form-urlencoded",
      },
     data = data_dict
  )

  print("Status: ", r.status_code)
  print("Bytes: ", len(r.content))
  print("Content-Type: ", r.headers.get('content-type'))

  return r.content

In [5]:
url = "https://unstats.un.org/sdgapi/v1/sdg/Series/DataCSV"

UNHC_dicts= {'seriesCodes': "SH_ACS_UNHC_25"}
MatMort_dict = {'seriesCodes': "SH_STA_MORT"}
HIV_dict = {'seriesCodes': "SH_HIV_INCD"}
Diseases_dict = {'seriesCodes': "SH_DTH_NCOM"}

#-------------------------------------------------------------------------

UNHC_data = get_content(url, UNHC_dicts)
with open("SH_ACS_UNHC_25.csv", "wb") as f:
    f.write(UNHC_data)

Maternal_Mortality_data = get_content(url, MatMort_dict)
with open("SH_STA_MORT.csv", "wb") as f:
    f.write(Maternal_Mortality_data)

HIV_data = get_content(url, HIV_dict)
with open("SH_HIV_INCD.csv", "wb") as f:
    f.write(HIV_data)

Diseases_data = get_content(url, Diseases_dict)
with open("SH_DTH_NCOM.csv", "wb") as f:
    f.write(Diseases_data)

Status:  200
Bytes:  2097152
Content-Type:  application/octet-stream
Status:  200
Bytes:  2097152
Content-Type:  application/octet-stream
Status:  200
Bytes:  33554432
Content-Type:  application/octet-stream
Status:  200
Bytes:  4194304
Content-Type:  application/octet-stream

In [6]:
UNHC_df = pd.read_csv("SH_ACS_UNHC_25.csv")
UNHC_df.head()

,Goal,Target,Indicator,SeriesCode,SeriesDescription,GeoAreaCode,GeoAreaName,TimePeriod,Value,Time_Detail,TimeCoverage,UpperBound,LowerBound,BasePeriod,Source,GeoInfoUrl,FootNote,[Nature],[Reporting Type],[Units]
0,3.0,3.8,3.8.1,SH_ACS_UNHC_25,Universal health coverage (UHC) service covera...,1.0,World,2000.0,54.0,2000.0,NaN,NaN,NaN,NaN,"WHO Global Health Observatory (GHO),December 2...",NaN,NaN,N,G,INDEX
1,3.0,3.8,3.8.1,SH_ACS_UNHC_25,Universal health coverage (UHC) service covera...,1.0,World,2001.0,54.0,2001.0,NaN,NaN,NaN,NaN,"WHO Global Health Observatory (GHO),December 2...",NaN,NaN,N,G,INDEX
2,3.0,3.8,3.8.1,SH_ACS_UNHC_25,Universal health coverage (UHC) service covera...,1.0,World,2002.0,55.0,2002.0,NaN,NaN,NaN,NaN,"WHO Global Health Observatory (GHO),December 2...",NaN,NaN,N,G,INDEX
3,3.0,3.8,3.8.1,SH_ACS_UNHC_25,Universal health coverage (UHC) service covera...,1.0,World,2003.0,55.0,2003.0,NaN,NaN,NaN,NaN,"WHO Global Health Observatory (GHO),December 2...",NaN,NaN,N,G,INDEX
4,3.0,3.8,3.8.1,SH_ACS_UNHC_25,Universal health coverage (UHC) service covera...,1.0,World,2004.0,56.0,2004.0,NaN,NaN,NaN,NaN,"WHO Global Health Observatory (GHO),December 2...",NaN,NaN,N,G,INDEX

In [7]:
MatMort_df = pd.read_csv("SH_STA_MORT.csv")
MatMort_df.head()

,Goal,Target,Indicator,SeriesCode,SeriesDescription,GeoAreaCode,GeoAreaName,TimePeriod,Value,Time_Detail,...,Source,GeoInfoUrl,FootNote,[Age],[Freq],[Location],[Nature],[Reporting Type],[Sex],[Units]
0,3.0,3.1,3.1.1,SH_STA_MORT,Maternal mortality ratio,1.0,World,2000.0,327.62899,2000.0,...,MMEIG estimates available at https://www.who.i...,NaN,NaN,NaN,NaN,NaN,N,G,FEMALE,PER_100000_LIVE_BIRTHS
1,3.0,3.1,3.1.1,SH_STA_MORT,Maternal mortality ratio,1.0,World,2001.0,321.17522,2001.0,...,MMEIG estimates available at https://www.who.i...,NaN,NaN,NaN,NaN,NaN,N,G,FEMALE,PER_100000_LIVE_BIRTHS
2,3.0,3.1,3.1.1,SH_STA_MORT,Maternal mortality ratio,1.0,World,2002.0,311.38922,2002.0,...,MMEIG estimates available at https://www.who.i...,NaN,NaN,NaN,NaN,NaN,N,G,FEMALE,PER_100000_LIVE_BIRTHS
3,3.0,3.1,3.1.1,SH_STA_MORT,Maternal mortality ratio,1.0,World,2003.0,300.77099,2003.0,...,MMEIG estimates available at https://www.who.i...,NaN,NaN,NaN,NaN,NaN,N,G,FEMALE,PER_100000_LIVE_BIRTHS
4,3.0,3.1,3.1.1,SH_STA_MORT,Maternal mortality ratio,1.0,World,2004.0,290.93301,2004.0,...,MMEIG estimates available at https://www.who.i...,NaN,NaN,NaN,NaN,NaN,N,G,FEMALE,PER_100000_LIVE_BIRTHS

In [8]:
HIV_df = pd.read_csv("SH_HIV_INCD.csv")
HIV_df.head()

/tmp/ipykernel_624/2620352931.py:1: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  HIV_df = pd.read_csv("SH_HIV_INCD.csv")

,Goal,Target,Indicator,SeriesCode,SeriesDescription,GeoAreaCode,GeoAreaName,TimePeriod,Value,Time_Detail,...,BasePeriod,Source,GeoInfoUrl,FootNote,[Age],[Nature],[Observation Status],[Reporting Type],[Sex],[Units]
0,3.0,3.3,3.3.1,SH_HIV_INCD,"Number of new HIV infections per 1,000 uninfec...",1.0,World,2000.0,0.48,2000.0,...,NaN,UNAIDS 2025 HIV ESTIMATES,NaN,NaN,ALLAGE,N,E,G,BOTHSEX,PER_1000_UNINFECTED_POP
1,3.0,3.3,3.3.1,SH_HIV_INCD,"Number of new HIV infections per 1,000 uninfec...",1.0,World,2000.0,0.66,2000.0,...,NaN,UNAIDS 2025 HIV ESTIMATES,NaN,NaN,15-49,N,E,G,MALE,PER_1000_UNINFECTED_POP
2,3.0,3.3,3.3.1,SH_HIV_INCD,"Number of new HIV infections per 1,000 uninfec...",1.0,World,2000.0,0.17,2000.0,...,NaN,UNAIDS 2025 HIV ESTIMATES,NaN,NaN,50+,N,E,G,MALE,PER_1000_UNINFECTED_POP
3,3.0,3.3,3.3.1,SH_HIV_INCD,"Number of new HIV infections per 1,000 uninfec...",1.0,World,2000.0,0.66,2000.0,...,NaN,UNAIDS 2025 HIV ESTIMATES,NaN,NaN,15-24,N,E,G,MALE,PER_1000_UNINFECTED_POP
4,3.0,3.3,3.3.1,SH_HIV_INCD,"Number of new HIV infections per 1,000 uninfec...",1.0,World,2000.0,0.13,2000.0,...,NaN,UNAIDS 2025 HIV ESTIMATES,NaN,NaN,50+,N,E,G,FEMALE,PER_1000_UNINFECTED_POP

In [9]:
Diseases_df = pd.read_csv("SH_DTH_NCOM.csv")
Diseases_df.head()

,Goal,Target,Indicator,SeriesCode,SeriesDescription,GeoAreaCode,GeoAreaName,TimePeriod,Value,Time_Detail,...,BasePeriod,Source,GeoInfoUrl,FootNote,[Age],[Name of non-communicable disease],[Nature],[Reporting Type],[Sex],[Units]
0,3.0,3.4,3.4.1,SH_DTH_NCOM,Mortality rate attributed to cardiovascular di...,1.0,World,2000.0,22.5,2000.0,...,NaN,"Global Health Estimates 2021: Deaths by Cause,...",NaN,Data was previously disseminated with a differ...,30-69,NaN,N,G,BOTHSEX,PERCENT
1,3.0,3.4,3.4.1,SH_DTH_NCOM,Mortality rate attributed to cardiovascular di...,1.0,World,2000.0,18.3,2000.0,...,NaN,"Global Health Estimates 2021: Deaths by Cause,...",NaN,Data was previously disseminated with a differ...,30-69,NaN,N,G,FEMALE,PERCENT
2,3.0,3.4,3.4.1,SH_DTH_NCOM,Mortality rate attributed to cardiovascular di...,1.0,World,2000.0,26.8,2000.0,...,NaN,"Global Health Estimates 2021: Deaths by Cause,...",NaN,Data was previously disseminated with a differ...,30-69,NaN,N,G,MALE,PERCENT
3,3.0,3.4,3.4.1,SH_DTH_NCOM,Mortality rate attributed to cardiovascular di...,1.0,World,2005.0,21.2,2005.0,...,NaN,"Global Health Estimates 2021: Deaths by Cause,...",NaN,Data was previously disseminated with a differ...,30-69,NaN,N,G,BOTHSEX,PERCENT
4,3.0,3.4,3.4.1,SH_DTH_NCOM,Mortality rate attributed to cardiovascular di...,1.0,World,2005.0,25.4,2005.0,...,NaN,"Global Health Estimates 2021: Deaths by Cause,...",NaN,Data was previously disseminated with a differ...,30-69,NaN,N,G,MALE,PERCENT

In [10]:
print("UNHC Shape:", UNHC_df.shape)
print("Maternal Mortality Shape:", MatMort_df.shape)
print("HIV Shape:", HIV_df.shape)
print("Diseases Shape:", Diseases_df.shape)

UNHC Shape: (5185, 20)
Maternal Mortality Shape: (5545, 24)
HIV Shape: (66301, 23)
Diseases Shape: (4327, 23)